# Generated by Django 4.2.6 on 2023-12-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_followinguser_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_likes',
        ),
    ]
