# Generated by Django 4.2.6 on 2023-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
