# Generated by Django 4.2.6 on 2023-10-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_slug_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
