# Generated by Django 4.2.6 on 2023-10-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_current_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='value',
        ),
    ]
